package com.ganeshdemo.cp4ba.casedetailstranslate;

import java.util.Locale;

import javax.servlet.http.HttpServletRequest;

import com.ibm.ecm.extension.PluginResponseFilter;
import com.ibm.ecm.extension.PluginServiceCallbacks;
import com.ibm.json.java.JSONArray;
import com.ibm.json.java.JSONObject;

/**
 * Provides an abstract class that is extended to create a filter for responses
 * from a particular service. The response from the service is provided to the
 * filter in JSON format before it is returned to the web browser. The filter
 * can then modify that response, and the modified response is returned to the
 * web browser.
 */
public class CaseDetailsTranslate extends PluginResponseFilter {

	/**
	 * Returns an array of the services that are extended by this filter.
	 * 
	 * @return A <code>String</code> array of names of the services. These are the
	 *         servlet paths or Struts action names.
	 */
	public String[] getFilteredServices() {
		return new String[] { "/p8/search" };
	}

	/**
	 * Filters the response from the service.
	 * 
	 * @param serverType   A <code>String</code> that indicates the type of server
	 *                     that is associated with the service. This value can be
	 *                     one or more of the following values separated by commas:
	 *                     <table border="1">
	 *                     <tr>
	 *                     <th>Server Type</th>
	 *                     <th>Description</th>
	 *                     </tr>
	 *                     <tr>
	 *                     <td><code>p8</code></td>
	 *                     <td>IBM FileNet P8</td>
	 *                     </tr>
	 *                     <tr>
	 *                     <td><code>cm</code></td>
	 *                     <td>IBM Content Manager</td>
	 *                     </tr>
	 *                     <tr>
	 *                     <td><code>od</code></td>
	 *                     <td>IBM Content Manager OnDemand</td>
	 *                     </tr>
	 *                     <tr>
	 *                     <td><code>cmis</code></td>
	 *                     <td>Content Management Interoperability Services</td>
	 *                     </tr>
	 *                     <tr>
	 *                     <td><code>common</code></td>
	 *                     <td>For services that are not associated with a
	 *                     particular server</td>
	 *                     </tr>
	 *                     </table>
	 * @param callbacks    An instance of the
	 *                     <code>{@link com.ibm.ecm.extension.PluginServiceCallbacks PluginServiceCallbacks}</code> class
	 *                     that contains functions that can be used by the service.
	 *                     These functions provide access to plug-in configuration
	 *                     and content server APIs.
	 * @param request      An <code>HttpServletRequest</code> object that provides
	 *                     the request. The service can access the invocation
	 *                     parameters from the request.
	 * @param jsonResponse The <code>JSONObject</code> object that is generated by
	 *                     the service. Typically, this object is serialized and
	 *                     sent as the response. The filter modifies this object to
	 *                     change the response that is sent.
	 * @throws Exception For exceptions that occur when the service is running.
	 *                   Information about the exception is logged as part of the
	 *                   client logging and an error response is automatically
	 *                   generated and returned.
	 */
	public void filter(String serverType, PluginServiceCallbacks callbacks, HttpServletRequest request,
			JSONObject jsonResponse) throws Exception {

		Locale locale = request.getLocale();
		System.out.println("requestnow:" + locale);
		String lang = locale.getLanguage();
		System.out.println("localeNow=----" + lang);

		JSONArray rows = (JSONArray) jsonResponse.get("rows");
		int size = 0;
		if (rows != null)
			size = rows.size();
		System.out.println("rows size-" + size);

		String currentLocationAttribute = "";
		if (jsonResponse.get("template_name") != null) {
			String template_name = jsonResponse.get("template_name").toString();
			System.out.println("template_name-" + template_name);
			if (template_name != null) {
				String tempName = template_name.split("_")[0];
				System.out.println("tempName-" + tempName);
				if (tempName.equalsIgnoreCase("DEMPAPPM")) {
					currentLocationAttribute = "DEMPAPPM_CurrentLocation";
				} else {
					currentLocationAttribute = "DEMPAPPAD_CurrentLocation";
				}
			} else {
				System.out.println("temp name is empty");
			}
		} else {
			System.out.println("template is empty");
		}

		if (!currentLocationAttribute.isEmpty()) {
			for (int i = 0; i < size; i++) {
				JSONObject obj = (JSONObject) rows.get(i);
				JSONObject attr = (JSONObject) obj.get("attributes");
				JSONArray fStep = (JSONArray) attr.get(currentLocationAttribute);

				if (fStep != null && !fStep.isEmpty()) {
					String futureStep = "";
					if (fStep.get(0) != null) {
						futureStep = fStep.get(0).toString();
					}

					System.out.println("futureStep-" + futureStep);
					if (futureStep.contains("DEMPAPP_") || futureStep.contains("HeadofEconomicsSection")) {
						futureStep = futureStep.replace("_DEV", "");
						futureStep = futureStep.replace("_Dev", "");
						futureStep = futureStep.replace("_dev", "");

						futureStep = futureStep.replace("[", "");
						futureStep = futureStep.replace("]", "");
						// futureStep = futureStep.replace("[]","");
						if (lang.equalsIgnoreCase("ar")) {
							futureStep = futureStep.replace("Review", "مراجعة");
						} else {
							futureStep = futureStep.replace("Review", "Review");
						}
						fStep.set(0, futureStep);
						attr.put(currentLocationAttribute, fStep);
						obj.put("attributes", attr);
						rows.set(i, obj);
						System.out.println("Replaced -" + i);
					}
				}
			}
		}

	}
}
